article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('software/', views.software, name='software'),
    path('math/',views.math, name='math'),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name='addArticle')
    
    
    
    
    
]

udemical/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path('articles/', include('article.urls', 'articles')),
    path('user/',include('user.urls','user')),
    path('about/', views.about, name="about"),
    path('contact/',views.contact, name="contact" )
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE, verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField(verbose_name="İçerik")
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")

    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms

class Login(forms.Form):
    username=forms.CharField(label="Kullanıcı Adı")
    password=forms.CharField(label="Parola",widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    username=forms.CharField(max_length=50, label="Kullanıcı Adı")
    password=forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Parolayı Doğrula",widget=forms.PasswordInput)

    def clean(self):
        username=self.cleaned_data.get("username")
        password= self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError('Parolalar Eşleşmiyor')
        
        values ={
            "username":username,
            "password":password,

        }
        return values
    

article/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.shortcuts import render, get_object_or_404
from .models import *
from article.form import ArticleForm
from django.contrib import messages

# Create your views here.



def software(request):
    articles = Article.objects.all()
    return render(request, 'software/software.html', {'articles': articles})

def math(request):
    return render(request,'math/math.html')



def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    context = {'article': article}
    return render(request, 'software/article_detail/article_detail.html', context)

def dashboard(request):
    return render(request,'dashboard/dashboard.html')

def addArticle(request):
    form = ArticleForm(request.POST or None)
    if form.iss_valid():
        form.save()
        messages.success(request,'Makale oluşturuldu.')
        return redirect('index')
    content = {
        'form':form
    }
    return render(request,'articles/addArticle.html',content)

udemical/views.py
from django.shortcuts import render,HttpResponse
from django.shortcuts import render, get_object_or_404

def index(request):
    return render(request,'home/index.html' )
def about(request):
    return render (request,'about/about.html')
def contact(request):
    return render(request,'contact/contact.html')

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm
from .forms import Login
from django.contrib.auth.models import User 
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages


# Create your views here.
def register(request):
    if request.method=="POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            newUser = User(username=username)
            newUser.set_password(password)
            newUser.save()
            messages.success(request,"Başarıyla kayıt oldunuz.")

            login(request,newUser)
            return redirect("index")
        else:
            context={
                "form":form
            }
            return render(request,"register/register.html",context)
    else:
        form= RegisterForm()
        context={
            "form":form
        }
        return render(request,"register/register.html",context)
   
def loginUser(request):
    form= Login(request.POST or None)
    context={
        "form":form
    }
    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")
        user=authenticate(username=username,password=password)
        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,'login/login.html',context)
        messages.success(request,"Başarıyla Giriş Yapıldı.  ",)
        login(request,user)
        return redirect("index")
    return render(request,'login/login.html',context)




def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yapıldı")
    return redirect('index')

templates/about/about.html
{% extends "home/layout.html" %} {% block body %}
<p class="container mt-5">
  Merhaba! İsmim Umur Savut ve Kuleli Askeri Lisesi'nden mezun oldum. Eğitim
  hayatımda başarıyla tamamladığım İngilizce ve Matematik bölümlerindeki
  mezuniyetimle akademik bir temel oluşturdum. Öğretmenlik kariyerime başlamadan
  önce 6 yıl boyunca aktif olarak öğretmenlik yaparak bilgi ve deneyim
  birikimimi arttırdım. <br />
  Öğretmenlik deneyimim sırasında, öğrencilerime bilgi aktarımını sadece sınıf
  ortamında değil, onları ilgilendiren ve etkileşimli hale getiren yöntemlerle
  gerçekleştirmeyi amaçladım. Öğrencilerimin gelişimini desteklemek için
  yenilikçi öğretim metotlarına ve teknolojik araçlara büyük önem verdim. Ancak,
  zamanla yazılıma olan ilgim giderek arttı ve web teknolojileriyle tanıştıkça
  bu alanda kendimi geliştirmeye başladım. İki yıldan beri yazılım geliştirme
  konusunda aktif olarak çalışıyor ve web teknolojilerine odaklanıyorum. Bu süre
  zarfında, çeşitli projelerde yer aldım ve farklı yazılım dilleriyle çalışarak
  geniş bir beceri yelpazesi kazandım.
  <br />
  <br />
  Yazılım geliştirme yolculuğumda, web uygulamaları ve siteleri tasarlama ve
  oluşturma konularında uzmanlaştım. HTML, CSS ve JavaScript gibi temel web
  teknolojilerini etkin bir şekilde kullanmayı öğrendim. Ayrıca, güncel web
  trendlerini takip ederek kullanıcı dostu ve yenilikçi çözümler sunmaya özen
  gösterdim. Yazılım geliştirme sürecinde, kullanıcı deneyimini optimize etmek
  ve hızlı, güvenilir ve ölçeklenebilir çözümler sunmak için çeşitli web
  çerçevelerini ve kütüphanelerini kullanıyorum.
  <br />
  <br />
  Back-end tarafında da deneyim sahibiyim ve JavaScript-Node.js ve Python gibi
  dillerle çalışarak veritabanı yönetimi ve sunucu tarafı geliştirmeleri
  yapabiliyorum. Öğretmenlik deneyimimden edindiğim analitik ve iletişim
  becerilerimi, yazılım geliştirme sürecinde de etkin bir şekilde kullanıyorum.
  Problem çözme yeteneğim ve ekip çalışmasına yatkınlığım, projelerdeki başarıyı
  arttırmama yardımcı oluyor. Yazılım geliştirme alanındaki tutkumu, öğrenmeye
  ve kendimi geliştirmeye olan isteğimi kullanarak her yeni projede daha da
  ilerlemeyi hedefliyorum. Yaratıcı ve özgün çözümler üretmeyi seviyor ve
  teknolojinin gücünü kullanarak kullanıcılarına değer katmayı amaçlıyorum.
  <br /><br />
  Bu süreçte edindiğim bilgi ve deneyimleri, yazılım projeleriyle ilgilenen
  kişilerle paylaşmayı ve onlara rehberlik etmeyi seviyorum. Sizlere de yazılım
  geliştirme konusunda yardımcı olabileceğimden eminim. Umarım sizlere, hem
  öğretmenlik hem de yazılım geliştirme alanındaki deneyimlerimle ilgili biraz
  daha kapsamlı bir bilgi sunabilmişimdir. Herhangi bir sorunuz varsa, sormaktan
  çekinmeyin. Size yardımcı olmaktan mutluluk duyarım.
</p>
{% endblock body %}

templates/articles/addArticle.html
{% extends 'home/layout.html' %}
{% include 'includes/navbar.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="mt-5 col-md-6 offset-md-3">
      <h3>GİRİŞ YAP</h3>
      <hr />
      <form method="POST">
        {% csrf_token %} {{ form|crispy }}
       <button class="btn btn-danger w-50" type="submit">Ekle</button>
      </form>
    </div>
  </div>
{% endblock body %}

templates/dashboard/dashboard.html
{% extends 'home/layout.html' %}
{% block body %}
<div class="container mt-5" >

<h3 class=" text-center" >KONTROL PANELİ </h3>
<p class=" text-center " >
<hr>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="{% url 'articles:addArticle' %}" >Makale Ekle</a>
<hr>














{% endblock body %}
</div>

templates/home/index.html
{% extends "home/layout.html" %} {% block body %}

  {% include 'includes/hero.html' %}
{%endblock body %}

templates/home/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>BLOG</title>
  </head>

  <body>
    {% include "includes/navbar.html" %}
    {% if messages %}
  
      {% for message in messages %}
      <div{% if message.tags %} class=" align-items-center  text-xl-center  alet alert-{{ message.tags }} "{% endif %}>{{ message }}</div>
    {% endfor %}
 
  {% endif %} 
    <div>{% block body %} {% endblock body %}</div>
   
    

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/includes/hero.html
{% load static %}
<style>
  body,
  html {
    height: 100%;
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
  }

  .hero-image {
    position: relative;

    height: 93vh;
  }

  .hero-text {
    text-align: center;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    color: white;
    z-index: 1;
  }

  .hero-text button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 10px 25px;
    color: black;
    background-color: orange;
    text-align: center;
    cursor: pointer;
    border-radius: 50px;
  }

  .hero-text button:hover {
    background-color: #555;
    color: white;
  }

  .hero-img {
    position: absolute;
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center;
    z-index: -1;
  }
</style>
<div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size: 50px" class="text-danger">Ben Umur SAVUT</h1>
    <p class="text-white">Full Stack Web Developer</p>
    <button class="text-white bg-danger">İletişime Geç</button>
  </div>
  <img class="hero-img" src="{% static 'img/1.jpg' %}" alt="" />
</div>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">YB</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav ">
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'articles:software' %}"
            >Blog Yazılarım</a
          >
        </li>
        <li class="nav-item"> 
          <a class="nav-link text-white" href="{% url 'articles:math' %}">Matematik</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'about' %}">Hakkımda</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'contact' %}">İletişim</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'articles:dashboard'%}"
            >Kontrol Paneli</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link " href="/user/logout/">Çıkış Yap</a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav ml-auto ">
        <li class="nav-item">
          <a class="nav-link text-white" href="/user/login/">Giriş Yap</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white" href="/user/register/">Kayıt Ol</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
  crossorigin="anonymous"
></script>

templates/includes/slider.html
{% load static %} {% extends "home/layout.html" %} {% block slider %}
<div id="mySlider" class="carousel slide" data-ride="carousel">
  <!-- Slider içeriği -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="Slide 1" />
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="Slide 2" />
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="Slide 3" />
    </div>
  </div>

  <!-- Slider gezinme düğmeleri -->
  <a
    class="carousel-control-prev"
    href="#mySlider"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Önceki</span>
  </a>
  <a
    class="carousel-control-next"
    href="#mySlider"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Sonraki</span>
  </a>
</div>
{% endblock slider %}

templates/login/login.html
{% extends 'home/layout.html' %} {% load crispy_forms_tags %} {% block body %}
<div class="row">
  <div class="mt-5 col-md-6 offset-md-3">
    <h3>GİRİŞ YAP</h3>
    <hr />
    <form method="POST">
      {% csrf_token %} {{ form|crispy }}
      <button type="submit" class="btn btn-danger">Giriş Yap</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/math/math.html
{% extends 'home/layout.html' %}
{% load static %}
{% block body %}
BURASI MATEMATİK SAYFASI OLACAKTIR

{% endblock body %}

templates/register/register.html
{% extends 'home/layout.html' %} {% load crispy_forms_tags %} {% block body %}
<div class="row">
  <div class="mt-5 col-md-6 offset-md-3">
    <h3>Kayıt Ol</h3>
    <hr />
    <form method="POST">
      {% csrf_token %} {{ form|crispy }}
      <button type="submit" class="btn btn-danger">Kayıt Ol</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/software/article_detail/article_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>BLOG</title>
  </head>

  <body>
    {% include "includes/navbar.html" %}

    <div class="card mt-5">
      <div class="card-body">
        <h5 class="card-header text-lg text-center">{{article.title}}</h5>
        <p class="card-text text-center">{{ article.content|safe }}</p>
        <a href="{% url 'index'  %}" class="btn btn-primary item"
          >Go somewhere</a
        >
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/software/software.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    {% include "includes/navbar.html" %}
    <div class="container">
      <div class="row justify-content-center">
        {% for article in articles %}
        <div class="col-md-4">
          <div class="card mt-5">
            <div class="card-body">
              <h5 class="card-header text-lg text-center">{{article.title}}</h5>
              <p class="card-text text-center">
                {{ article.content|truncatechars:150 |safe }}
              </p>
              <a
                href="{% url 'articles:article_detail' article.id %}"
                class="btn btn-primary item"
                >Go somewhere</a
              >
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>